# Generated by Django 4.0.3 on 2022-04-07 05:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('societyapp', '0005_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 5, 55, 25, 384452, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='flat_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='tower_no',
            field=models.IntegerField(default=0),
        ),
    ]
