# Generated by Django 4.0.3 on 2022-04-13 11:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('societyapp', '0012_complain_news_visitor_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 11, 36, 39, 964424, tzinfo=utc)),
        ),
    ]
