# Generated by Django 4.0.3 on 2022-04-13 11:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('societyapp', '0013_alter_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='gender',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 11, 46, 40, 495885, tzinfo=utc)),
        ),
    ]
