# Generated by Django 4.0.3 on 2022-04-13 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('societyapp', '0014_remove_visitor_gender_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='gender',
            field=models.TextField(default='Male'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 12, 10, 32, 840338, tzinfo=utc)),
        ),
    ]
