# Generated by Django 4.0.3 on 2022-04-15 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('societyapp', '0017_alter_user_date_joined_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('mobile', models.TextField()),
                ('type', models.TextField()),
                ('amount', models.TextField()),
                ('members', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('house_type', models.TextField()),
                ('facilities', models.TextField()),
                ('message', models.TextField()),
                ('furnish', models.TextField()),
                ('bank', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 15, 11, 53, 11, 157840, tzinfo=utc)),
        ),
    ]
